# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  pull_request:
  schedule:
    - cron: "0 2 * * 6"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.8 ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py

      - name: Install
        run: pip install pytest -e . --only-binary=numpy,scipy,matplotlib,torch
        env:
          PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu

      - name: Test with pytest
        run: python -m pytest -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: setup.py

      - name: Lint with flake8
        run: |
          python -m pip install flake8
          python -m flake8 .
